# Generated by Django 5.0.7 on 2024-08-06 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_post_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="friend",
            new_name="friends",
        ),
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 5, 21, 18, 26, 149896)
            ),
        ),
    ]
