# Generated by Django 4.1 on 2024-07-06 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
