# Generated by Django 4.1 on 2024-07-06 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0005_post"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
