# Generated by Django 4.1 on 2024-07-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0006_alter_post_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.SlugField(),
        ),
    ]
