# Generated by Django 4.1 on 2024-07-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0007_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
