# Generated by Django 4.1 on 2024-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0011_alter_friendrequest_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(default="sent", max_length=20),
        ),
    ]
