# Generated by Django 4.1 on 2024-07-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0012_friendrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
