# Generated by Django 4.1 on 2024-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0013_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
