# Generated by Django 4.1 on 2024-07-08 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0014_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 7, 22, 16, 10, 206710)
            ),
        ),
    ]
