# Generated by Django 4.1 on 2024-07-09 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0015_alter_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 8, 18, 49, 0, 822494)
            ),
        ),
    ]
